- name: "{{ COPY_NAME }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: 'yes'
  with_items:
    - { src: "test.txt", dest: "{{ tmp_dir }}/test.txt" }
  register: copy_test
- debug: var=copy_test.results