- name: 设置SELINUX为disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
    state: present
    backup: 'yes'
  ignore_errors: true

- name: 确保sudoers中没有wheel组
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    state: absent
    backup: yes

- name: 在hosts中以127.0.0.1开头的行替换为127.0.0.1 localhost
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost'
    owner: root
    group: root
    mode: '0644'
    state: present
    backup: yes

- name: 在/tmp/testfile中添加一行
  lineinfile:
    path: /tmp/testfile
    line: "This is a test line {{ LINEINFILE_NAME }}"
    create: yes
    state: present
